### ISSUE TITLE
error creating map

### ISSUE THREAD

**Issue by avogadro21** [manifestinteractive/jqvmap#306]
Hello, i'm having trouble while creating a new map, when i run command python jqvmap.py config/example.json this error occured

Traceback (most recent call last):
  File "jqvmap.py", line 4, in <module>
    import shapely.wkb
  File "C:\Python27\lib\site-packages\shapely-1.2.16-py2.7.egg\shapely\wkb.py",
line 6, in <module>
    from shapely.geos import lgeos, ReadingError
  File "C:\Python27\lib\site-packages\shapely-1.2.16-py2.7.egg\shapely\geos.py",
 line 71, in <module>
    _lgeos = CDLL("geos.dll")
  File "C:\Python27\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

can anyone help me what i should do?
thanks for your help before

**Comment by manifestinteractive** [comment]
@avogadro21 I am nowhere near a Python expert so maybe someone here can help with your issue.
